// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/graph.proto

/*
Package graph is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/framework/graph.proto

It has these top-level messages:
	GraphDef
*/
package graph

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow5 "github.com/ouwen/minflow_serve_proto/tensorflow/core/framework/node_def"
import tensorflow7 "github.com/ouwen/minflow_serve_proto/tensorflow/core/framework/function"
import tensorflow8 "github.com/ouwen/minflow_serve_proto/tensorflow/core/framework/versions"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Represents the graph of operations
type GraphDef struct {
	Node []*tensorflow5.NodeDef `protobuf:"bytes,1,rep,name=node" json:"node,omitempty"`
	// Compatibility versions of the graph.  See core/public/version.h for version
	// history.  The GraphDef version is distinct from the TensorFlow version, and
	// each release of TensorFlow will support a range of GraphDef versions.
	Versions *tensorflow8.VersionDef `protobuf:"bytes,4,opt,name=versions" json:"versions,omitempty"`
	// Deprecated single version field; use versions above instead.  Since all
	// GraphDef changes before "versions" was introduced were forward
	// compatible, this field is entirely ignored.
	Version int32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// EXPERIMENTAL. DO NOT USE OR DEPEND ON THIS YET.
	//
	// "library" provides user-defined functions.
	//
	// Naming:
	//   * library.function.name are in a flat namespace.
	//     NOTE: We may need to change it to be hierarchical to support
	//     different orgs. E.g.,
	//     { "/google/nn", { ... }},
	//     { "/google/vision", { ... }}
	//     { "/org_foo/module_bar", { ... }}
	//     map<string, FunctionDefLib> named_lib;
	//   * If node[i].op is the name of one function in "library",
	//     node[i] is deemed as a function call. Otherwise, node[i].op
	//     must be a primitive operation supported by the runtime.
	//
	//
	// Function call semantics:
	//
	//   * The callee may start execution as soon as some of its inputs
	//     are ready. The caller may want to use Tuple() mechanism to
	//     ensure all inputs are ready in the same time.
	//
	//   * The consumer of return values may start executing as soon as
	//     the return values the consumer depends on are ready.  The
	//     consumer may want to use Tuple() mechanism to ensure the
	//     consumer does not start until all return values of the callee
	//     function are ready.
	Library *tensorflow7.FunctionDefLibrary `protobuf:"bytes,2,opt,name=library" json:"library,omitempty"`
}

func (m *GraphDef) Reset()                    { *m = GraphDef{} }
func (m *GraphDef) String() string            { return proto.CompactTextString(m) }
func (*GraphDef) ProtoMessage()               {}
func (*GraphDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GraphDef) GetNode() []*tensorflow5.NodeDef {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GraphDef) GetVersions() *tensorflow8.VersionDef {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *GraphDef) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GraphDef) GetLibrary() *tensorflow7.FunctionDefLibrary {
	if m != nil {
		return m.Library
	}
	return nil
}

func init() {
	proto.RegisterType((*GraphDef)(nil), "tensorflow.GraphDef")
}

func init() { proto.RegisterFile("tensorflow/core/framework/graph.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd1, 0x4f, 0x6b, 0xbb, 0x30,
	0x18, 0x07, 0x70, 0xd2, 0xf6, 0xf7, 0x6b, 0x89, 0x37, 0x07, 0x23, 0x8c, 0x31, 0x64, 0x30, 0xe6,
	0xc9, 0x80, 0xbb, 0xec, 0x2c, 0xb2, 0x5d, 0xc6, 0x28, 0x1e, 0x76, 0xd8, 0x45, 0xfc, 0xf3, 0xc4,
	0xca, 0x6a, 0x9e, 0xf2, 0xa8, 0x95, 0xbd, 0xba, 0xbd, 0xad, 0x1d, 0x87, 0xb1, 0xb6, 0x5e, 0xb6,
	0xde, 0xc4, 0x7c, 0x9e, 0x6f, 0xf2, 0x4d, 0xf8, 0x5d, 0x03, 0xba, 0x46, 0x52, 0x5b, 0xec, 0x64,
	0x86, 0x04, 0x52, 0x51, 0x52, 0x41, 0x87, 0xf4, 0x21, 0x0b, 0x4a, 0x76, 0x1b, 0x6f, 0x47, 0xd8,
	0xa0, 0xcd, 0x4f, 0xec, 0xca, 0xfd, 0x7d, 0x44, 0x63, 0x0e, 0x71, 0x0e, 0x6a, 0x98, 0xfa, 0x4b,
	0xaa, 0x56, 0x67, 0x4d, 0x89, 0xfa, 0xbc, 0xdc, 0x03, 0xd5, 0x25, 0xea, 0x7a, 0x90, 0xb7, 0x5f,
	0x8c, 0xaf, 0x9e, 0xfb, 0x93, 0x85, 0xa0, 0xec, 0x7b, 0xbe, 0xe8, 0xb7, 0x14, 0xcc, 0x99, 0xbb,
	0x96, 0x7f, 0xe1, 0x9d, 0x52, 0xbc, 0x57, 0xcc, 0x21, 0x04, 0x15, 0x19, 0x60, 0xfb, 0x7c, 0x35,
	0xe6, 0x88, 0x85, 0xc3, 0x5c, 0xcb, 0xbf, 0x9c, 0xe2, 0xb7, 0x61, 0xad, 0xf7, 0x47, 0x67, 0x5f,
	0xf3, 0xe5, 0xe1, 0x5b, 0xcc, 0x1d, 0xe6, 0xfe, 0x0b, 0x66, 0x82, 0x45, 0xe3, 0x2f, 0xfb, 0x91,
	0x2f, 0xb7, 0x65, 0x4a, 0x09, 0x7d, 0x8a, 0x99, 0x09, 0xbc, 0x99, 0x06, 0x3e, 0x1d, 0xea, 0x85,
	0xa0, 0x5e, 0x06, 0x15, 0x8d, 0x3c, 0x20, 0x2e, 0x90, 0x8a, 0xa9, 0x3e, 0x96, 0x0d, 0x2c, 0x53,
	0x6d, 0xdd, 0x37, 0xad, 0xd7, 0xec, 0x3d, 0x2c, 0xca, 0x66, 0xd3, 0xa6, 0x5e, 0x86, 0x95, 0xc4,
	0xb6, 0x03, 0x2d, 0xab, 0x52, 0xf7, 0x23, 0x71, 0x0d, 0xb4, 0x87, 0xd8, 0x5c, 0x89, 0x3c, 0xf3,
	0x84, 0xdf, 0x8c, 0xa5, 0xff, 0x8d, 0x7c, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x62, 0x15,
	0xc4, 0xef, 0x01, 0x00, 0x00,
}
