// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/regression.proto

/*
Package regression is a generated protocol buffer package.

It is generated from these files:
	protobuf/regression.proto

It has these top-level messages:
	Regression
	RegressionResult
	RegressionRequest
	RegressionResponse
*/
package regression

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow_serving "github.com/ouwen/minflow_serve_proto/protobuf/input"
import tensorflow_serving1 "github.com/ouwen/minflow_serve_proto/protobuf/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Regression result for a single item (tensorflow.Example).
type Regression struct {
	Value float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
}

func (m *Regression) Reset()                    { *m = Regression{} }
func (m *Regression) String() string            { return proto.CompactTextString(m) }
func (*Regression) ProtoMessage()               {}
func (*Regression) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Regression) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Contains one result per input example, in the same order as the input in
// RegressionRequest.
type RegressionResult struct {
	Regressions []*Regression `protobuf:"bytes,1,rep,name=regressions" json:"regressions,omitempty"`
}

func (m *RegressionResult) Reset()                    { *m = RegressionResult{} }
func (m *RegressionResult) String() string            { return proto.CompactTextString(m) }
func (*RegressionResult) ProtoMessage()               {}
func (*RegressionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegressionResult) GetRegressions() []*Regression {
	if m != nil {
		return m.Regressions
	}
	return nil
}

type RegressionRequest struct {
	// Model Specification.
	ModelSpec *tensorflow_serving1.ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec" json:"model_spec,omitempty"`
	// Input data.
	Input *tensorflow_serving.Input `protobuf:"bytes,2,opt,name=input" json:"input,omitempty"`
}

func (m *RegressionRequest) Reset()                    { *m = RegressionRequest{} }
func (m *RegressionRequest) String() string            { return proto.CompactTextString(m) }
func (*RegressionRequest) ProtoMessage()               {}
func (*RegressionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegressionRequest) GetModelSpec() *tensorflow_serving1.ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *RegressionRequest) GetInput() *tensorflow_serving.Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type RegressionResponse struct {
	Result *RegressionResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *RegressionResponse) Reset()                    { *m = RegressionResponse{} }
func (m *RegressionResponse) String() string            { return proto.CompactTextString(m) }
func (*RegressionResponse) ProtoMessage()               {}
func (*RegressionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegressionResponse) GetResult() *RegressionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Regression)(nil), "tensorflow.serving.Regression")
	proto.RegisterType((*RegressionResult)(nil), "tensorflow.serving.RegressionResult")
	proto.RegisterType((*RegressionRequest)(nil), "tensorflow.serving.RegressionRequest")
	proto.RegisterType((*RegressionResponse)(nil), "tensorflow.serving.RegressionResponse")
}

func init() { proto.RegisterFile("protobuf/regression.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xbf, 0x4b, 0xc3, 0x40,
	0x18, 0x86, 0xb9, 0x4a, 0x0b, 0x7e, 0x59, 0xf4, 0xe8, 0x90, 0x0a, 0x4a, 0x09, 0x0e, 0x9d, 0xee,
	0xa0, 0x2e, 0x0e, 0x15, 0xc4, 0xcd, 0xc1, 0xe5, 0x74, 0x72, 0x09, 0x26, 0x7e, 0x8d, 0x07, 0xc9,
	0xdd, 0x79, 0x3f, 0xda, 0xdd, 0xbf, 0xda, 0x51, 0x72, 0xa9, 0x6d, 0xc4, 0x40, 0xb7, 0xe4, 0xe5,
	0x79, 0x3e, 0xde, 0x37, 0x81, 0x99, 0xb1, 0xda, 0xeb, 0x22, 0xac, 0xb9, 0xc5, 0xca, 0xa2, 0x73,
	0x52, 0x2b, 0x16, 0x33, 0x4a, 0x3d, 0x2a, 0xa7, 0xed, 0xba, 0xd6, 0x5b, 0xe6, 0xd0, 0x6e, 0xa4,
	0xaa, 0x2e, 0xa6, 0x7b, 0x5c, 0x2a, 0x13, 0x7c, 0x47, 0xf6, 0xd2, 0x46, 0xbf, 0x63, 0xdd, 0xa5,
	0x59, 0x06, 0x20, 0xf6, 0x37, 0xe9, 0x14, 0xc6, 0x9b, 0xb7, 0x3a, 0x60, 0x4a, 0xe6, 0x64, 0x31,
	0x12, 0xdd, 0x4b, 0xf6, 0x02, 0x67, 0x07, 0x46, 0xa0, 0x0b, 0xb5, 0xa7, 0xf7, 0x90, 0x1c, 0xba,
	0xb8, 0x94, 0xcc, 0x4f, 0x16, 0xc9, 0xf2, 0x8a, 0xfd, 0x6f, 0xc3, 0x7a, 0x6a, 0x5f, 0xc9, 0xbe,
	0x08, 0x9c, 0xf7, 0xcf, 0x7e, 0x06, 0x74, 0x9e, 0xae, 0x00, 0x62, 0xbd, 0xdc, 0x19, 0x2c, 0x63,
	0x8d, 0x64, 0x79, 0x39, 0x74, 0xf6, 0xa9, 0xa5, 0x9e, 0x0d, 0x96, 0xe2, 0xb4, 0xf9, 0x7d, 0xa4,
	0x1c, 0xc6, 0x71, 0x72, 0x3a, 0x8a, 0xe2, 0x6c, 0x48, 0x7c, 0x6c, 0x01, 0xd1, 0x71, 0x99, 0x00,
	0xfa, 0x67, 0x9a, 0xd1, 0xca, 0x21, 0x5d, 0xc1, 0xc4, 0xc6, 0x99, 0xbb, 0x02, 0xd7, 0x47, 0x76,
	0x45, 0x56, 0xec, 0x9c, 0x87, 0xbb, 0xd7, 0xdb, 0x4a, 0xfa, 0x8f, 0x50, 0xb0, 0x52, 0x37, 0x5c,
	0x87, 0x2d, 0x2a, 0xde, 0x48, 0xd5, 0xca, 0x79, 0x2b, 0x63, 0x1e, 0x3f, 0x3d, 0x1f, 0xf8, 0xa9,
	0xdf, 0x84, 0x14, 0x93, 0x98, 0xdf, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x38, 0xf9, 0x03,
	0xf5, 0x01, 0x00, 0x00,
}
