// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/tensor_shape.proto

/*
Package tensor_shape is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/framework/tensor_shape.proto

It has these top-level messages:
	TensorShapeProto
*/
package tensor_shape

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Dimensions of a tensor.
type TensorShapeProto struct {
	// Dimensions of the tensor, such as {"input", 30}, {"output", 40}
	// for a 30 x 40 2D tensor.  If an entry has size -1, this
	// corresponds to a dimension of unknown size. The names are
	// optional.
	//
	// The order of entries in "dim" matters: It indicates the layout of the
	// values in the tensor in-memory representation.
	//
	// The first entry in "dim" is the outermost dimension used to layout the
	// values, the last entry is the innermost dimension.  This matches the
	// in-memory layout of RowMajor Eigen tensors.
	//
	// If "dim.size()" > 0, "unknown_rank" must be false.
	Dim []*TensorShapeProto_Dim `protobuf:"bytes,2,rep,name=dim" json:"dim,omitempty"`
	// If true, the number of dimensions in the shape is unknown.
	//
	// If true, "dim.size()" must be 0.
	UnknownRank bool `protobuf:"varint,3,opt,name=unknown_rank,json=unknownRank" json:"unknown_rank,omitempty"`
}

func (m *TensorShapeProto) Reset()                    { *m = TensorShapeProto{} }
func (m *TensorShapeProto) String() string            { return proto.CompactTextString(m) }
func (*TensorShapeProto) ProtoMessage()               {}
func (*TensorShapeProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TensorShapeProto) GetDim() []*TensorShapeProto_Dim {
	if m != nil {
		return m.Dim
	}
	return nil
}

func (m *TensorShapeProto) GetUnknownRank() bool {
	if m != nil {
		return m.UnknownRank
	}
	return false
}

// One dimension of the tensor.
type TensorShapeProto_Dim struct {
	// Size of the tensor in that dimension.
	// This value must be >= -1, but values of -1 are reserved for "unknown"
	// shapes (values of -1 mean "unknown" dimension).  Certain wrappers
	// that work with TensorShapeProto may fail at runtime when deserializing
	// a TensorShapeProto containing a dim value of -1.
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	// Optional name of the tensor dimension.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *TensorShapeProto_Dim) Reset()                    { *m = TensorShapeProto_Dim{} }
func (m *TensorShapeProto_Dim) String() string            { return proto.CompactTextString(m) }
func (*TensorShapeProto_Dim) ProtoMessage()               {}
func (*TensorShapeProto_Dim) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *TensorShapeProto_Dim) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TensorShapeProto_Dim) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TensorShapeProto)(nil), "tensorflow.TensorShapeProto")
	proto.RegisterType((*TensorShapeProto_Dim)(nil), "tensorflow.TensorShapeProto.Dim")
}

func init() { proto.RegisterFile("tensorflow/core/framework/tensor_shape.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x1a, 0x21, 0x70, 0x19, 0x20, 0x93, 0xc5, 0x64, 0x98, 0x32, 0x80, 0x2d, 0x95,
	0x7f, 0x50, 0x75, 0x63, 0xa9, 0x0c, 0x13, 0x4b, 0xe4, 0x96, 0x6b, 0x6b, 0x05, 0xdf, 0x55, 0x76,
	0x42, 0x24, 0x16, 0xfe, 0x06, 0x3f, 0x95, 0x11, 0xd9, 0x20, 0x8a, 0x32, 0xb1, 0x3d, 0x3f, 0x7f,
	0x4f, 0x77, 0xef, 0xc4, 0x4d, 0x07, 0x98, 0x28, 0x6e, 0x5e, 0x68, 0x30, 0x6b, 0x8a, 0x60, 0x36,
	0xd1, 0x05, 0x18, 0x28, 0xb6, 0xe6, 0xfb, 0xa7, 0x49, 0x3b, 0xb7, 0x07, 0xbd, 0x8f, 0xd4, 0x51,
	0x25, 0x0e, 0xf4, 0xf5, 0x07, 0x13, 0xe7, 0x8f, 0xe5, 0xf9, 0x90, 0x89, 0x65, 0x01, 0x66, 0x82,
	0x3f, 0xfb, 0x20, 0x27, 0x8a, 0xd7, 0xd3, 0x99, 0xd2, 0x07, 0x5c, 0x8f, 0x51, 0xbd, 0xf0, 0xc1,
	0x66, 0xb8, 0xba, 0x12, 0x67, 0x3d, 0xb6, 0x48, 0x03, 0x36, 0xd1, 0x61, 0x2b, 0xb9, 0x62, 0xf5,
	0x89, 0x9d, 0xfe, 0x78, 0xd6, 0x61, 0x7b, 0x79, 0x2b, 0xf8, 0xc2, 0x87, 0xaa, 0x12, 0x47, 0xc9,
	0xbf, 0x81, 0x64, 0x8a, 0xd5, 0xdc, 0x16, 0x9d, 0x3d, 0x74, 0x01, 0xe4, 0x44, 0xb1, 0xfa, 0xd4,
	0x16, 0x3d, 0x7f, 0x17, 0x92, 0xe2, 0xf6, 0xef, 0xf4, 0xdf, 0x56, 0xf3, 0x8b, 0xf1, 0x22, 0x69,
	0xc9, 0x9e, 0xee, 0xb7, 0xbe, 0xdb, 0xf5, 0x2b, 0xbd, 0xa6, 0x60, 0xa8, 0x1f, 0x00, 0x4d, 0xf0,
	0x98, 0x83, 0x4d, 0x82, 0xf8, 0x0a, 0x4d, 0x69, 0x6f, 0xfe, 0x77, 0xaa, 0x4f, 0xc6, 0x56, 0xc7,
	0x25, 0x70, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xa6, 0xaf, 0xbe, 0x5e, 0x01, 0x00, 0x00,
}
